const { chromium } = require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const assert = require('node:assert/strict');
const { pathToFileURL } = require('node:url');
const path = require('node:path');
(async () => {
  for (const executablePath of (process.env.PRESENTATION_BROWSERS ? JSON.parse(process.env.PRESENTATION_BROWSERS) : [undefined])) {
    const browser = await chromium.launch({ executablePath, headless: true });
    const context = await browser.newContext({ offline: true, viewport: { width: 1440, height: 900 } });
    const page = await context.newPage();
    const errors = [], external = [];
    page.on('pageerror', e => errors.push(e.message));
    page.on('request', r => { if (/^https?:/.test(r.url())) external.push(r.url()); });
    await page.goto(pathToFileURL(path.resolve(__dirname, '../apresentacao/ResolvAI.html')).href);
    await page.getByRole('button', { name: 'Entrar', exact: true }).waitFor();
    assert.match(page.url(), /#\/login$/);
    await page.getByRole('link', { name: 'Crie uma agora' }).click();
    await page.getByLabel('Nome completo').waitFor();
    for (const width of [1440, 390, 320]) {
      await page.setViewportSize({ width, height: 900 });
      assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth), false, 'signup overflow ' + width);
      const background = await page.locator('.login-container').boundingBox();
      assert.ok(background.x <= 0 && background.width >= width && background.height >= 900, 'full signup background ' + width);
    }
    await page.setViewportSize({ width: 1440, height: 900 });
    await page.getByLabel('Nome completo').fill('Professora Demonstração');
    await page.getByLabel('E-mail', { exact: true }).fill('professora@example.invalid');
    await page.getByLabel('Senha', { exact: true }).fill('DemoTeste123');
    await page.getByLabel('Confirmar senha').fill('Diferente123');
    await page.getByRole('button', { name: 'Criar conta', exact: true }).click();
    await page.getByText('As senhas não coincidem. Verifique e tente novamente.', { exact: true }).waitFor();
    await page.getByLabel('Confirmar senha').fill('DemoTeste123');
    await page.getByRole('button', { name: 'Criar conta', exact: true }).click();
    await page.getByLabel('E-mail', { exact: true }).fill('professora@example.invalid');
    await page.getByLabel('Senha', { exact: true }).fill('DemoTeste123');
    await page.getByRole('button', { name: 'Entrar', exact: true }).click();
    await page.getByRole('heading', { name: /Olá, Ygor/ }).waitFor();
    await page.getByRole('tab', { name: 'Em andamento', exact: true }).click();
    assert.equal(await page.locator('.order-card').count(), 1);
    await page.getByRole('tab', { name: 'Em andamento', exact: true }).press('Home');
    assert.equal(await page.locator('.order-card').count(), 2);
    await page.getByRole('searchbox', { name: 'Buscar pedido' }).fill('infiltração');
    assert.equal(await page.locator('.order-card').count(), 1);
    await page.getByRole('searchbox', { name: 'Buscar pedido' }).fill('não existe');
    await page.getByRole('button', { name: 'Limpar filtros', exact: true }).click();
    assert.equal(await page.locator('.order-card').count(), 2);
    await page.getByRole('button', { name: 'Ver propostas', exact: true }).click();
    await page.getByRole('button', { name: /Tenho interesse/ }).first().click();
    await page.getByRole('status').filter({ hasText: /Interesse registrado/ }).waitFor();
    await page.getByRole('button', { name: 'Notificações, 3 não lidas', exact: true }).click();
    await page.getByRole('dialog').getByRole('heading', { name: 'Suas notificações', exact: true }).waitFor();
    await page.keyboard.press('Escape');
    assert.equal(await page.locator('.notification-button i').count(), 0);
    await page.getByRole('button', { name: 'Ver histórico de serviços', exact: true }).click();
    await page.getByRole('dialog').getByRole('heading', { name: 'Histórico de serviços', exact: true }).waitFor();
    await page.keyboard.press('Escape');
    await page.getByRole('button', { name: 'Central de ajuda', exact: true }).click();
    await page.getByText('Como criar um pedido?', { exact: true }).click();
    assert.equal(await page.locator('details[open]').count(), 1);
    await page.keyboard.press('Escape');
    for (const [label, title] of [['Propostas','Propostas recebidas'],['Mensagens','Conversa com o prestador'],['Contratos','Meus contratos'],['Pagamentos','Pagamentos'],['Avaliações','Minhas avaliações']]) {
      await page.locator('.sidebar').getByRole('button', { name: new RegExp('^' + label + '(?: \\d+)?$') }).click();
      await page.getByRole('dialog').getByRole('heading', { name: title, exact: true }).waitFor();
      if (label === 'Mensagens') {
        await page.getByRole('textbox', { name: 'Sua mensagem' }).fill('Mensagem de teste offline');
        await page.getByRole('button', { name: 'Enviar mensagem de demonstração' }).click();
        await page.getByText('Mensagem de teste offline', { exact: true }).waitFor();
      }
      await page.keyboard.press('Escape');
    }
    await page.getByRole('button', { name: 'Abrir meu perfil' }).click();
    await page.getByLabel('Nome', { exact: true }).fill('Diego Apresentação');
    await page.getByRole('button', { name: 'Salvar alterações' }).click();
    await page.getByRole('heading', { name: /Olá, Diego/ }).waitFor();
    await page.getByRole('button', { name: 'Meus pedidos', exact: true }).click();
    await page.locator('a[href*="/pedidos/1042"]').click();
    await page.getByRole('heading', { name: /Pedido #1042/ }).waitFor();
    await page.reload();
    await page.getByRole('heading', { name: /Pedido #1042/ }).waitFor();
    await page.getByRole('button', { name: 'Visão geral', exact: true }).click();
    await page.locator('.sidebar').getByRole('button', { name: 'Criar pedido', exact: true }).click();
    await page.getByRole('button', { name: 'Pintura', exact: true }).click();
    await page.getByLabel('Descreva seu problema').fill('Quero pintar as paredes da sala.');
    await page.getByRole('button', { name: 'Enviar resposta' }).click();
    await page.getByRole('button', { name: 'Não sei informar esses detalhes' }).click();
    await page.getByRole('button', { name: 'Enviar resposta' }).click();
    await page.getByRole('button', { name: 'Pode esperar', exact: true }).click();
    await page.locator('#scope-photos').setInputFiles({ name: 'foto-demo.png', mimeType: 'image/png', buffer: Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+aD1sAAAAASUVORK5CYII=', 'base64') });
    await page.getByRole('button', { name: 'Continuar com as fotos' }).click();
    await page.getByRole('button', { name: 'Revisar escopo', exact: true }).click();
    assert.equal(await page.locator('.scope-review img').count(), 1);
    await page.getByLabel('Título do pedido').fill('Pintura para apresentação');
    await page.getByLabel('Escopo sugerido').fill('Escopo editado para apresentação.');
    await page.getByRole('button', { name: 'Voltar à conversa', exact: true }).click();
    await page.getByRole('button', { name: 'Revisar escopo', exact: true }).click();
    assert.equal(await page.getByLabel('Escopo sugerido').inputValue(), 'Escopo editado para apresentação.');
    await page.getByRole('button', { name: 'Publicar pedido', exact: true }).click();
    await page.getByRole('button', { name: 'Meus pedidos', exact: true }).click();
    await page.getByRole('heading', { name: /Pintura para apresentação/ }).waitFor();
    await page.locator('.my-orders-list article').first().getByRole('link', { name: /Ver detalhes/ }).click();
    await page.getByText('Escopo editado para apresentação.', { exact: true }).waitFor();
    assert.equal(await page.locator('.scope-photos img').count(), 1);
    await page.getByRole('button', { name: 'Visão geral', exact: true }).click();
    await page.getByRole('button', { name: 'Abrir meu perfil' }).click();
    await page.getByLabel('Nome', { exact: true }).fill('Diego Apresentação');
    await page.getByRole('button', { name: 'Salvar alterações' }).click();
    await page.locator('.sidebar').getByRole('button', { name: 'Mensagens', exact: true }).click();
    await page.getByRole('textbox', { name: 'Sua mensagem' }).fill('Mensagem mantida ao mostrar login');
    await page.getByRole('button', { name: 'Enviar mensagem de demonstração' }).click();
    await page.keyboard.press('Escape');
    await page.getByRole('link', { name: 'Login', exact: true }).click();
    await page.getByRole('link', { name: 'Esqueceu a senha?' }).click();
    await page.getByText(/A recuperação de senha não está conectada nesta demonstração/).waitFor();
    await page.getByRole('link', { name: 'Abrir demonstração sem login' }).click();
    await page.getByRole('heading', { name: /Olá, Diego/ }).waitFor();
    await page.getByRole('button', { name: 'Meus pedidos', exact: true }).click();
    await page.getByRole('heading', { name: /Pintura para apresentação/ }).waitFor();
    await page.getByRole('button', { name: 'Visão geral', exact: true }).click();
    await page.locator('.sidebar').getByRole('button', { name: 'Mensagens', exact: true }).click();
    await page.getByText('Mensagem mantida ao mostrar login', { exact: true }).waitFor();
    await page.keyboard.press('Escape');
    for (const width of [1440, 768, 390, 320]) {
      await page.setViewportSize({ width, height: 900 });
      assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth), false, 'overflow ' + width);
    }
    assert.deepEqual(errors, []);
    assert.deepEqual(external, []);
    console.log('PASS full offline regression: ' + executablePath + ' — login, signup, validation, filters, keyboard tabs, interest, notifications, history, help, menus, chat, profile, photos, edited scope, creation, details, refresh and responsive layouts; no network or JS errors.');
    await browser.close();
  }
})().catch(e => { console.error(e); process.exit(1); });
